### ISSUE TITLE
Ctrl-C Overwrites Multiple Line Inputs and Hisotry Search

### ISSUE THREAD

**Issue by mitnk** [murarth/linefeed#38]
Pretty like #35, There are two `Ctrl-C` overwrite issues.

(`III` means the cursor position)

1. when cancel an input:

```
$ echo III you typed a long long
line command, and decide to cancel with Ctrl-C
# Ctrl-C makes prompt overwrite `line command, ...` line.
```

and 2. when searching history with `Ctrl-R`:

```
(reverse-i-search)`curl': curl III -i http://a-very-very-
long-url.com/which-wraps-lines/
# Ctrl-C also overwrite the second line
```

**Comment by murarth** [comment]
I'm working on a big set of changes right now and, while the solution to this issue is fairly small, it does touch a few pieces of code that are being moved around, so I'm going to hold off until that big changeset lands to save myself further merge headaches. Hopefully, I don't take too long to finish up the big changes.

You can leave this issue open until then.
