### ISSUE TITLE
Seems to be a bug in terminfo, or something else in the place where the term is loaded.

### ISSUE THREAD

**Issue by driftluo** [murarth/linefeed#49]
On archLinux, when `TERM = xterm-256color`, linefeed will not start, and no error message, it can't load `xterm-256color`. But in Ubuntu and Mac, it can works well.

You can reproduce this by downloading the docker image of `base/archlinux` and loading the locally compiled executable into it.

Default  TERM is `xterm`, it's works well.
```bash
[root@b634483af1a5 release]# export
declare -x HOME="/root"
declare -x HOSTNAME="b634483af1a5"
declare -x OLDPWD="/home/luoc/Rust-work/cita-cli/luoc/Rust-work/cita-cli/target/x86_64-unknown-linux-musl"
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PWD="/home/luoc/Rust-work/cita-cli/luoc/Rust-work/cita-cli/target/x86_64-unknown-linux-musl/release"
declare -x SHLVL="1"
declare -x TERM="xterm"
```
But if you use `xterm-256color`, it doesn't work, and has nothing to output
```bash
[root@b634483af1a5 release]# TERM=xterm-256color ./cita-cli 
```
`xterm-256color` is already on `/lib/terminfo/x/`
```bash
[root@b634483af1a5 release]# ls /lib/terminfo/x/ | grep xterm-256
xterm-256color
```
Related issue：https://github.com/cryptape/cita-cli/pull/51 https://github.com/cryptape/cita-cli/issues/16

**Comment by murarth** [comment]
Hm. I thought this issue should have been solved by a recent update. There may still be an older version of `terminfo` in your `Cargo.lock` file. Try running `cargo update` in the project folder and see if that fixes it.

If you still experience the issue with the latest version of `terminfo` (which is currently `0.6.0`), then you should file an issue on that project.

And as for the silent failure, this is because `cita-cli` is ignoring the error value (see [here](https://github.com/cryptape/cita-cli/blob/master/cita-cli/src/main.rs#L73)).

**Comment by driftluo** [comment]
Oh, thank you very much, I am ignoring the wrong code is not correct.

I saw my `Cargo.lock`, the version of `terminfo` is indeed 0.6.0, but this problem exists. After opening the error, I get an error, as follows:
```bash
[root@b634483af1a5 release]# TERM=xterm-256color ./cita-cli 
failed to parse terminfo entry
```
I will open an issue to `terminfo`
