### ISSUE TITLE
Concurrent history access

### ISSUE THREAD

**Issue by stepancheg** [murarth/linefeed#57]
It's not currently possible to save history from two processes into the same history file.

Consider this scenario:

process1 loads history
process2 loads history
process1 collects history lines
process2 collects history lines
process1 saves history
process2 saves history

History collected from process1 is lost.

AFAIU to fix this situation, linefeed can:

* separately store loaded and collected history
* before saving history to disk, reload "loaded" history from the history file

**Comment by murarth** [comment]
I've just pushed a commit to fix this issue. The solution I've implemented is a bit different than the one you've suggested, but I believe the effect is the same:

* Track the number of history entries added since last save/load
* On save, append latest *n* entries to the file

Thank you for this issue. Let me know if it works as expected.

**Comment by stepancheg** [comment]
Just checked, seems to be working as expected. Thanks!
