### ISSUE TITLE
Window size calculating issue when using color in prompt

### ISSUE THREAD

**Issue by mitnk** [murarth/linefeed#6]
When using crate like `ansi_term` to render colored text in `reader.set_prompt()`, linefeed seems also count the unprintable color chars into length. The result is the input area for user of the line looks shorter, and will wrap into the second line before hitting end of this line.

```
xxx@yyy:  zzz $ echo 000000000000000000000               # <-- end of terminal line
000000000000
```

**Comment by murarth** [comment]
You'll have to manually signal to `linefeed` where the "invisible" portions of the prompt are because it doesn't understand what constitutes an ANSI escape sequence. The docs for [`Reader::set_prompt`](https://docs.rs/linefeed/0.2.2/linefeed/reader/struct.Reader.html#method.set_prompt) describe how to do this.

**Comment by mitnk** [comment]
Ah, I should read the docs more careful.. Thanks @murarth!
