### ISSUE TITLE
Function execute with mut self not available

### ISSUE THREAD

**Issue by tacsnack** [murarth/linefeed#60]
Is there a way to get control sequences to influence the state of the overall application? My use case would be to catch a certain sequence (ie: ctrl-Q) and then toggle a variable to indicate the mode that the application should operate in. I was looking at the function examples, but both use the execute(&self, ...) which does not allow for writing to self. I am relatively new to rust so let me know if I am sorry if I am missing something obvious here. 

Thanks,

**Comment by murarth** [comment]
For internal structural reasons, the `Function` trait must accept `&self` instead of `&mut self`. However, there is a workaround to this requirement.

The way to do this is through what is broadly termed "interior mutability." This means using types like [`Cell`](https://doc.rust-lang.org/std/cell/struct.Cell.html) and [`RefCell`](https://doc.rust-lang.org/std/cell/struct.RefCell.html) or their multi-threaded counterparts, [atomic types](https://doc.rust-lang.org/std/sync/atomic/index.html) and [`Mutex`](https://doc.rust-lang.org/std/sync/struct.Mutex.html). These types use internal locking mechanisms to allow controlled mutable access to their contents when accessed with `&self`.

In this case, either atomics or `Mutex` are required, as types implementing the `Function` trait must be thread-safe.

**Comment by tacsnack** [comment]
Thanks for the help and information. I figured it was designed that way for a reason. I appreciate you taking the time to give me some direction on this. Also, for creating this great library!
