### ISSUE TITLE
Windows CMD and PowerShell non-black background color

### ISSUE THREAD

**Issue by AE9RB** [murarth/linefeed#63]
Use a standard Windows 10 install, launch PowerShell. The background will be blue unless you changed it. Run the example/demo program. Type a backspace. The line will turn black. You can also use CMD but will have to change the background color to something other than black in the preferences.

The new Windows Terminal and the terminal in my editor work correctly. WSL also works even though it uses conhost.exe like CMD and PowerShell.

**Comment by murarth** [comment]
The root cause of this bug is in the [`mortal`](https://github.com/murarth/mortal) crate, which linefeed uses for low-level cross-platform terminal functions (and which is also authored by me).

I've submitted a PR on that project that I believe would solve this issue. Can you test it and confirm? murarth/mortal#16

**Comment by AE9RB** [comment]
Works! Thank you.
